// Re-applies the size filters to an existing data/basemap.js (no network needed).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { pruneBasemap } from './basemap_filters.mjs';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const file = path.join(ROOT, 'data', 'basemap.js');
const src = fs.readFileSync(file, 'utf8');
const json = src.slice(src.indexOf('window.BKK_BASEMAP = ') + 'window.BKK_BASEMAP = '.length).replace(/;\s*$/, '');
const bm = JSON.parse(json);
const before = Object.fromEntries(Object.entries(bm.layers).map(([k, v]) => [k, `${v.features.length} / ${(JSON.stringify(v).length / 1e3).toFixed(0)} KB`]));
pruneBasemap(bm);
const out = JSON.stringify(bm);
fs.writeFileSync(file, `// Generated by scripts/build_basemap.mjs — do not edit by hand.\n// ${bm.attribution}\nwindow.BKK_BASEMAP = ${out};\n`);
const counts = Object.fromEntries(Object.entries(bm.layers).map(([k, v]) => [k, v.features.length]));
fs.writeFileSync(path.join(ROOT, 'data', 'basemap.meta.json'), JSON.stringify({ generated: bm.generated, bbox: bm.bbox, bytes: out.length, counts }, null, 2) + '\n');
console.log('before:', before); console.log('after :', counts, `${(out.length / 1e6).toFixed(2)} MB`);
